project:
  type: website
  output-dir: docs

website:
  title: "R for Demographic Data Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Topics
        menu:
          - href: intro.qmd
            text: Introduction
          - href: maps.qmd
            text: Creating Maps
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

